name: New

on:
    push:
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

# Hello there