name: Prepare Release
run-name: Prepare v${{ github.event.inputs.versionNumber }} Release

on:
    workflow_dispatch:
        inputs:
            versionNumber:
                description: 'Version number being released (excluding the "v" prefix)'
                required: true
                type: string
            releaseDate:
                description: 'Anticipated release date'
                required: true
                type: string
            wikiLink:
                description: 'Link to release notes wiki page for this release'
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}
  VERSION_NUMBER: ${{ github.event.inputs.versionNumber }}
  RELEASE_DATE: ${{ github.event.inputs.releaseDate }}
  WIKI_LINK: ${{ github.event.inputs.wikiLink }}
  RELEASE_BRANCH_NAME: release/${{ github.event.inputs.versionNumber }}

jobs:
    prepare-release:
        name: Prepare Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Configure Git
              run: |
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com

            - name: Get develop branch name
              id: develop-branch
              run: |
                if git branch --all --contains remotes/origin/develop; then
                    echo "DEVELOP_BRANCH=remotes/origin/develop" >> $GITHUB_OUTPUT;
                elif git branch --all --contains remotes/origin/Develop; then
                    echo "DEVELOP_BRANCH=remotes/origin/Develop" >> $GITHUB_OUTPUT;
                else
                    echo "::error::Unable to find develop branch";
                    exit 1;
                fi
 
            - name: Create release branch
              env:
                DEVELOP_BRANCH: ${{ steps.develop-branch.outputs.DEVELOP_BRANCH }}
              run: git switch --create ${{ env.RELEASE_BRANCH_NAME }} ${{ env.DEVELOP_BRANCH }}
   
            - name: Update RELEASENOTES.md
              run: |
                python ./.github/workflows/update_release_notes.py ${{ env.VERSION_NUMBER }} ${{ env.RELEASE_DATE }} ${{ env.WIKI_LINK }}
                git add RELEASENOTES.md
                git commit --message "Update RELEASENOTES.md"

            - name: Push release branch
              run: git push --set-upstream origin ${{ env.RELEASE_BRANCH_NAME }}
 
            - name: Create default branch pull request
              id: create-default-pr
              run: gh pr create --title "Release v${{ env.VERSION_NUMBER }}" --body "Release v${{ env.VERSION_NUMBER }}"

            - name: Create develop branch pull request
              env:
                DEVELOP_BRANCH: ${{ steps.develop-branch.outputs.DEVELOP_BRANCH }}
              run: gh pr create --title "Release v${{ env.VERSION_NUMBER }}" --body "Release v${{ env.VERSION_NUMBER}}" --base ${{ env.DEVELOP_BRANCH }}
            
            - name: Cleanup on failure
              if: failure()
              run: |
                gh pr close ${{ env.RELEASE_BRANCH_NAME }}
                git push --delete origin ${{ env.RELEASE_BRANCH_NAME }}
