name: prepare-release

on:
    workflow_dispatch:
        inputs:
            versionNumber:
                description: 'Version number being released (excluding the "v" prefix)'
                required: true
                type: string
            releaseNotesLink:
                description: 'Link to release notes wiki page for this release'
                required: true
                type: string
            releaseDate:
                description: 'Anticipated release date'
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    prepare-release:
        name: Prepare Release
        runs-on: ubuntu-latest
        env:
            RELEASE_BRANCH_NAME: Release/${{ github.event.inputs.versionNumber }}
            VERSION_NUMBER: v${{ github.event.inputs.versionNumber }}
        steps:
            - uses: actions/checkout@v2
 
            - name: Create release branch
              run: git switch -c ${{ env.RELEASE_BRANCH_NAME }} develop
            - name: Create release branch
              if: failure()
              run: git switch -c ${{ env.RELEASE_BRANCH_NAME }} Develop
   
        #     name: Updates RELEASENOTES.md
        #     steps:
        #         - run:
 
            - name: Push release branch
              run: git push -u origin ${{ env.RELEASE_BRANCH_NAME }}
 
            - name: Create default branch pull request
              run: gh pr create --title "Release/${{ env.RELEASE_BRANCH_NAME }}" --body "Release ${{ env.VERSION_NUMBER }}"

            - name: Create develop branch pull request
              run: gh pr create --title "Release/${{ env.RELEASE_BRANCH_NAME }}" --body "Release ${{ env.VERSION_NUMBER}}" --base develop
            - name: Create Develop branch pull request
              if: failure()
              run: gh pr create --title "Release/${{ env.RELEASE_BRANCH_NAME }}" --body "Release ${{ env.VERSION_NUMBER}}" --base Develop