name: prepare-release

on:
    workflow_dispatch:
        inputs:
            versionNumber:
                description: 'Version number being released (excluding the "v" prefix)'
                required: true
                type: string
            releaseNotesLink:
                description: 'Link to release notes wiki page for this release'
                required: true
                type: string
            releaseDate:
                description: 'Anticipated release date'
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    prepare-release:
        name: Prepare Release
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
            RELEASE_BRANCH_NAME: Release/${{ github.event.inputs.versionNumber }}
            VERSION_NUMBER: ${{ github.event.inputs.versionNumber }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: List branches
              run: git branch --all --list

            - name: Get develop branch name
              id: develop-branch
              run: |
                if git branch --all --list remotes/origin/develop; then
                    echo "DEVELOP_BRANCH=remotes/origin/develop" >> $GITHUB_OUTPUT;
                else
                    echo "DEVELOP_BRANCH=remotes/origin/Develop" >> $GITHUB_OUTPUT;
                fi
 
            - name: Create release branch
              env:
                DEVELOP_BRANCH: ${{ steps.develop-branch.outputs.DEVELOP_BRANCH }}
              run: git switch --create ${{ env.RELEASE_BRANCH_NAME }} ${{ env.DEVELOP_BRANCH }}
   
        #     name: Updates RELEASENOTES.md
        #     steps:
        #         - run:
 
            - name: Push release branch
              run: git push --set-upstream origin ${{ env.RELEASE_BRANCH_NAME }}
 
            - name: Create default branch pull request
              run: gh pr create --title "Release/${{ env.VERSION_NUMBER }}" --body "Release ${{ env.VERSION_NUMBER }}"
              continue-on-error: true

            - name: Create develop branch pull request
              env:
                DEVELOP_BRANCH: ${{ steps.develop-branch.outputs.DEVELOP_BRANCH }}
              run: gh pr create --title "Release/v${{ env.VERSION_NUMBER }}" --body "Release v${{ env.VERSION_NUMBER}}" --base ${{ env.DEVELOP_BRANCH }}
              continue-on-error: true